### ISSUE TITLE
[DOCFIX] Missing Command in the Readme.MD

### ISSUE THREAD

**Issue by cb7chaitanya** [Piyush-linux/Lets-Learn-Git#1]

**Comment by Piyush-linux** [comment]
Mr. @cb7chaitanya, Please provide complete description :smile:

**Comment by cb7chaitanya** [comment]
Ok, I actually wanted to add git --version command as it is missing from the readme file and it will allow people to confirm that git is actually intalled in their machine, please assign me this issue @Piyush-linux

**Comment by cb7chaitanya** [comment]
I wanted to add git --version command @Piyush-linux

**Comment by vishalmaurya850** [comment]
Assign this issue to me as SSOC24 
I will add this git --version command
